# My first python project

## First steps
- install git on laptop (via VS Code Source Control)
- clone github repository (that Sarah has set up) via Source Control
- git repo is now saved on my local desktop as Github
- from View/Command Palette...  Create environment (.venv), this is a local environment
- create a branch from the main repo (ln/pandas_rewrite)
- add a requirements.txt file to include all packages I'll be using
- set up a jupyter notebook to test code and play with pandas
- save good code to a .py file

All these instructions will go into the main repo README file.

In [1]:
# import packages
import pandas as pd
import numpy as np

# import data
#df = pd.read_excel('C:/Users/laura.north/OneDrive - Swansea University/Documents/Training/Six Nations PP/points_predictor.xlsx', sheet_name="predictions")

# data
#df.head()

# get list of participants

In [2]:
# import data
df = pd.read_excel('C:/Users/laura.north/OneDrive - Swansea University/Documents/Training/Six Nations PP/pandas_attempt1.xlsx', sheet_name="predictions")

df.head()

   Round  Match Home Team Away Team     Name  Home Points  Away Points
0      1      1    France   Ireland       MP           22           30
1      1      1    France   Ireland   Mike P           22           30
2      1      1    France   Ireland  Glennnn           22           16
3      1      1    France   Ireland    Big D           24           20
4      1      1    France   Ireland    Jess            27           25

In [3]:
# get a list of participants
participants = df['Name'].unique()
participants

array(['MP', 'Mike P', 'Glennnn', 'Big D', 'Jess ', 'Elise', 'Stubert',
       'Wazza', 'OJ', 'The Hawk', 'Serith', 'Ethan', 'CBP', 'Ems', 'JC',
       'Leigh', 'Jon', 'Iesha', 'Keith', 'Ellie', 'The Baglan Strangler'],
      dtype=object)

In [4]:
df['HomeScoreDiff'] = df['Home Points']-df['Away Points']
df['Predict_Home_Win'] = df['HomeScoreDiff'].apply(lambda x: 1 if x > 0 else 0)
df

,Round,Match,Home Team,Away Team,Name,Home Points,Away Points,HomeScoreDiff,Predict_Home_Win
0,1,1,France,Ireland,MP,22,30,-8,0
1,1,1,France,Ireland,Mike P,22,30,-8,0
2,1,1,France,Ireland,Glennnn,22,16,6,1
3,1,1,France,Ireland,Big D,24,20,4,1
4,1,1,France,Ireland,Jess,27,25,2,1
...,...,...,...,...,...,...,...,...,...
121,2,3,Ireland,Italy,Jon,34,12,22,1
122,2,3,Ireland,Italy,Iesha,36,17,19,1
123,2,3,Ireland,Italy,Keith,45,10,35,1
124,2,3,Ireland,Italy,Ellie,40,15,25,1
125,2,3,Ireland,Italy,The Baglan Strangler,33,12,21,1

In [5]:
# after running Rich's web scraping tool, import results for 2024
res = pd.read_csv('data/SixNationsResults.csv')
res.head()

,Year,Round,Date,Stadium,HomeTeam,AwayTeam,FinalScoreHome,FinalScoreAway,HTScoreHome,HTScoreAway
0,2000,1,Sat 5 Feb,Stadio Flaminio,ITA,SCO,34,20,12,10
1,2000,1,Sat 5 Feb,Twickenham,ENG,IRE,50,18,25,3
2,2000,1,Sat 5 Feb,Principality Stadium,WAL,FRA,3,36,3,9
3,2000,2,Sat 19 Feb,Stade de France,FRA,ENG,9,15,0,9
4,2000,2,Sat 19 Feb,Principality Stadium,WAL,ITA,47,16,30,9

In [6]:
# filter to include 2024 rounds 1 and 2 only
res2024 = res[(res['Year']==2024) & (res['Round'].isin([1, 2]))]
res2024

,Year,Round,Date,Stadium,HomeTeam,AwayTeam,FinalScoreHome,FinalScoreAway,HTScoreHome,HTScoreAway
360,2024,1,Fri 2 Feb,Orange Velodrome,FRA,IRE,17,38,10,17
361,2024,1,Sat 3 Feb,Stadio Olimpico,ITA,ENG,24,27,17,14
362,2024,1,Sat 3 Feb,Principality Stadium,WAL,SCO,26,27,0,20
363,2024,2,Sat 10 Feb,Scottish Gas Murrayfield,SCO,FRA,16,20,13,10
364,2024,2,Sat 10 Feb,Twickenham,ENG,WAL,16,14,5,14
365,2024,2,Sun 11 Feb,Aviva Stadium,IRE,ITA,36,0,19,0

In [7]:
# flag whether home or away is winner
res2024['HomeScoreDiff'] = res2024['FinalScoreHome']-res2024['FinalScoreAway']
res2024['HomeWin'] = res2024['HomeScoreDiff'].apply(lambda x: 1 if x > 0 else 0)

# another way of calculating above
res2024['HomeWin2'] = 0
res2024.loc[(res2024['FinalScoreHome']>res2024['FinalScoreAway']), 'HomeWin2'] = 1

# add column for match number
res2024['Match'] = res2024.groupby('Round')['Round'].rank(method='first', ascending=True)
res2024['Match'] = res2024['Match'].apply(np.int64)
res2024

C:\Users\laura.north\AppData\Local\Temp\ipykernel_1716\2849433427.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res2024['HomeScoreDiff'] = res2024['FinalScoreHome']-res2024['FinalScoreAway']
C:\Users\laura.north\AppData\Local\Temp\ipykernel_1716\2849433427.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res2024['HomeWin'] = res2024['HomeScoreDiff'].apply(lambda x: 1 if x > 0 else 0)
C:\Users\laura.north\AppData\Local\Temp\ipykernel_1716\2849433427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res2024['HomeWin2'] = 0
C:\Users\laura.north\AppData\Local\Temp\ipykernel_1716\2849433427.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res2024['Match'] = res2024.groupby('Round')['Round'].rank(method='first', ascending=True)
C:\Users\laura.north\AppData\Local\Temp\ipykernel_1716\2849433427.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res2024['Match'] = res2024['Match'].apply(np.int64)

,Year,Round,Date,Stadium,HomeTeam,AwayTeam,FinalScoreHome,FinalScoreAway,HTScoreHome,HTScoreAway,HomeScoreDiff,HomeWin,HomeWin2,Match
360,2024,1,Fri 2 Feb,Orange Velodrome,FRA,IRE,17,38,10,17,-21,0,0,1
361,2024,1,Sat 3 Feb,Stadio Olimpico,ITA,ENG,24,27,17,14,-3,0,0,2
362,2024,1,Sat 3 Feb,Principality Stadium,WAL,SCO,26,27,0,20,-1,0,0,3
363,2024,2,Sat 10 Feb,Scottish Gas Murrayfield,SCO,FRA,16,20,13,10,-4,0,0,1
364,2024,2,Sat 10 Feb,Twickenham,ENG,WAL,16,14,5,14,2,1,1,2
365,2024,2,Sun 11 Feb,Aviva Stadium,IRE,ITA,36,0,19,0,36,1,1,3

In [8]:
# tidy up tables before merging (drop columns)
res2024 = res2024.drop(columns = ['Year', 'Date', 'Stadium', 'HTScoreHome', 'HTScoreAway', 'HomeScoreDiff', 'HomeWin2'])
res2024

     Round HomeTeam AwayTeam  FinalScoreHome  FinalScoreAway  HomeWin  Match
360      1      FRA      IRE              17              38        0      1
361      1      ITA      ENG              24              27        0      2
362      1      WAL      SCO              26              27        0      3
363      2      SCO      FRA              16              20        0      1
364      2      ENG      WAL              16              14        1      2
365      2      IRE      ITA              36               0        1      3

In [9]:
df = df.drop(columns = ['HomeScoreDiff'])

In [10]:
# merge tables
df2 = pd.merge(df, res2024, how="left", on=['Round', 'Match'])
df2

# need to add a match index to join, might also need to join on home team names at later date? or this could be a seperate table with key to join to each table

,Round,Match,Home Team,Away Team,Name,Home Points,Away Points,Predict_Home_Win,HomeTeam,AwayTeam,FinalScoreHome,FinalScoreAway,HomeWin
0,1,1,France,Ireland,MP,22,30,0,FRA,IRE,17,38,0
1,1,1,France,Ireland,Mike P,22,30,0,FRA,IRE,17,38,0
2,1,1,France,Ireland,Glennnn,22,16,1,FRA,IRE,17,38,0
3,1,1,France,Ireland,Big D,24,20,1,FRA,IRE,17,38,0
4,1,1,France,Ireland,Jess,27,25,1,FRA,IRE,17,38,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,2,3,Ireland,Italy,Jon,34,12,1,IRE,ITA,36,0,1
122,2,3,Ireland,Italy,Iesha,36,17,1,IRE,ITA,36,0,1
123,2,3,Ireland,Italy,Keith,45,10,1,IRE,ITA,36,0,1
124,2,3,Ireland,Italy,Ellie,40,15,1,IRE,ITA,36,0,1
125,2,3,Ireland,Italy,The Baglan Strangler,33,12,1,IRE,ITA,36,0,1

In [11]:
# create home and away score differences
df2['HomePredDiff'] = -(df2['Home Points'] - df2['FinalScoreHome']).abs()
df2['AwayPredDiff'] = -(df2['Away Points'] - df2['FinalScoreAway']).abs()
df2

# add a winning bonus (-10 points if result is incorrect)
df2['WinningBonus'] = -10
df2.loc[(df2['Predict_Home_Win']==df2['HomeWin']), 'WinningBonus'] = 0
df2

# correct score bonus
df2['CorrectHomeScore'] = 0
df2.loc[(df2['Home Points']==df2['FinalScoreHome']), 'CorrectHomeScore'] = 1
df2['CorrectAwayScore'] = 0
df2.loc[(df2['Away Points']==df2['FinalScoreAway']), 'CorrectAwayScore'] = 1
df2

#sense check
#df2.loc[(df2['CorrectAwayScore']==1)]

,Round,Match,Home Team,Away Team,Name,Home Points,Away Points,Predict_Home_Win,HomeTeam,AwayTeam,FinalScoreHome,FinalScoreAway,HomeWin,HomePredDiff,AwayPredDiff,WinningBonus,CorrectHomeScore,CorrectAwayScore
0,1,1,France,Ireland,MP,22,30,0,FRA,IRE,17,38,0,-5,-8,0,0,0
1,1,1,France,Ireland,Mike P,22,30,0,FRA,IRE,17,38,0,-5,-8,0,0,0
2,1,1,France,Ireland,Glennnn,22,16,1,FRA,IRE,17,38,0,-5,-22,-10,0,0
3,1,1,France,Ireland,Big D,24,20,1,FRA,IRE,17,38,0,-7,-18,-10,0,0
4,1,1,France,Ireland,Jess,27,25,1,FRA,IRE,17,38,0,-10,-13,-10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,2,3,Ireland,Italy,Jon,34,12,1,IRE,ITA,36,0,1,-2,-12,0,0,0
122,2,3,Ireland,Italy,Iesha,36,17,1,IRE,ITA,36,0,1,0,-17,0,1,0
123,2,3,Ireland,Italy,Keith,45,10,1,IRE,ITA,36,0,1,-9,-10,0,0,0
124,2,3,Ireland,Italy,Ellie,40,15,1,IRE,ITA,36,0,1,-4,-15,0,0,0
125,2,3,Ireland,Italy,The Baglan Strangler,33,12,1,IRE,ITA,36,0,1,-3,-12,0,0,0

In [12]:
# total difference of predicted vs actual scores
pred_score_diff = ['HomePredDiff', 'AwayPredDiff']
df2['TotalPredDiff'] = df2[pred_score_diff].sum(axis=1)
df2

# correct score bonus
correct_scores = ['CorrectHomeScore', 'CorrectAwayScore']
df2['BothScoresCorrect'] = df2[correct_scores].sum(axis=1)
df2['CorrectScoreBonus'] = 0
df2.loc[(df2['BothScoresCorrect']==2), 'CorrectAwayScore'] = 20
df2

,Round,Match,Home Team,Away Team,Name,Home Points,Away Points,Predict_Home_Win,HomeTeam,AwayTeam,...,FinalScoreAway,HomeWin,HomePredDiff,AwayPredDiff,WinningBonus,CorrectHomeScore,CorrectAwayScore,TotalPredDiff,BothScoresCorrect,CorrectScoreBonus
0,1,1,France,Ireland,MP,22,30,0,FRA,IRE,...,38,0,-5,-8,0,0,0,-13,0,0
1,1,1,France,Ireland,Mike P,22,30,0,FRA,IRE,...,38,0,-5,-8,0,0,0,-13,0,0
2,1,1,France,Ireland,Glennnn,22,16,1,FRA,IRE,...,38,0,-5,-22,-10,0,0,-27,0,0
3,1,1,France,Ireland,Big D,24,20,1,FRA,IRE,...,38,0,-7,-18,-10,0,0,-25,0,0
4,1,1,France,Ireland,Jess,27,25,1,FRA,IRE,...,38,0,-10,-13,-10,0,0,-23,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,2,3,Ireland,Italy,Jon,34,12,1,IRE,ITA,...,0,1,-2,-12,0,0,0,-14,0,0
122,2,3,Ireland,Italy,Iesha,36,17,1,IRE,ITA,...,0,1,0,-17,0,1,0,-17,1,0
123,2,3,Ireland,Italy,Keith,45,10,1,IRE,ITA,...,0,1,-9,-10,0,0,0,-19,0,0
124,2,3,Ireland,Italy,Ellie,40,15,1,IRE,ITA,...,0,1,-4,-15,0,0,0,-19,0,0
125,2,3,Ireland,Italy,The Baglan Strangler,33,12,1,IRE,ITA,...,0,1,-3,-12,0,0,0,-15,0,0

In [13]:
# closest bonus (smallest difference gets +5 points, but this will change after each game)
df2['ClosestScoreBonus'] = 0
df2.loc[df2['TotalPredDiff'].idxmax(), 'ClosestScoreBonus'] = 5
df2

df2.sort_values('ClosestScoreBonus', ascending=False)


# 3 correct results per round bonus - change this to be a seperate table instead and join on to round score table
df3 = df2.groupby(['Round', 'Name'])['WinningBonus'].sum().reset_index(name='SumWinningBonus')
df3

df3['CorrectRoundBonus'] = 0
df3.loc[(df3['SumWinningBonus']==0), 'CorrectRoundBonus'] = 5
df3

    Round                  Name  SumWinningBonus  CorrectRoundBonus
0       1                 Big D              -10                  0
1       1                   CBP              -20                  0
2       1                 Elise              -10                  0
3       1                 Ellie              -10                  0
4       1                   Ems              -10                  0
5       1                 Ethan              -20                  0
6       1               Glennnn              -20                  0
7       1                 Iesha              -10                  0
8       1                    JC              -10                  0
9       1                 Jess               -10                  0
10      1                   Jon              -10                  0
11      1                 Keith              -10                  0
12      1                 Leigh              -20                  0
13      1                    MP              -10                  0
14      1                Mike P              -10                  0
15      1                    OJ              -20                  0
16      1                Serith                0                  5
17      1               Stubert              -10                  0
18      1  The Baglan Strangler              -10                  0
19      1              The Hawk              -10                  0
20      1                 Wazza              -20                  0
21      2                 Big D                0                  5
22      2                   CBP                0                  5
23      2                 Elise                0                  5
24      2                 Ellie              -10                  0
25      2                   Ems              -10                  0
26      2                 Ethan              -10                  0
27      2               Glennnn              -20                  0
28      2                 Iesha              -10                  0
29      2                    JC              -10                  0
30      2                 Jess               -10                  0
31      2                   Jon                0                  5
32      2                 Keith              -10                  0
33      2                 Leigh              -10                  0
34      2                    MP                0                  5
35      2                Mike P                0                  5
36      2                    OJ                0                  5
37      2                Serith                0                  5
38      2               Stubert              -20                  0
39      2  The Baglan Strangler              -10                  0
40      2              The Hawk                0                  5
41      2                 Wazza              -10                  0

In [14]:
# calculate final scores (CorrectRoundBonus not included here, should ClosestScoreBonus be removed here too??)
calculate_final_score = ['TotalPredDiff', 'WinningBonus', 'CorrectScoreBonus', 'ClosestScoreBonus']
df2['FinalScore'] = df2[calculate_final_score].sum(axis=1)
df2

,Round,Match,Home Team,Away Team,Name,Home Points,Away Points,Predict_Home_Win,HomeTeam,AwayTeam,...,HomePredDiff,AwayPredDiff,WinningBonus,CorrectHomeScore,CorrectAwayScore,TotalPredDiff,BothScoresCorrect,CorrectScoreBonus,ClosestScoreBonus,FinalScore
0,1,1,France,Ireland,MP,22,30,0,FRA,IRE,...,-5,-8,0,0,0,-13,0,0,0,-13
1,1,1,France,Ireland,Mike P,22,30,0,FRA,IRE,...,-5,-8,0,0,0,-13,0,0,0,-13
2,1,1,France,Ireland,Glennnn,22,16,1,FRA,IRE,...,-5,-22,-10,0,0,-27,0,0,0,-37
3,1,1,France,Ireland,Big D,24,20,1,FRA,IRE,...,-7,-18,-10,0,0,-25,0,0,0,-35
4,1,1,France,Ireland,Jess,27,25,1,FRA,IRE,...,-10,-13,-10,0,0,-23,0,0,0,-33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,2,3,Ireland,Italy,Jon,34,12,1,IRE,ITA,...,-2,-12,0,0,0,-14,0,0,0,-14
122,2,3,Ireland,Italy,Iesha,36,17,1,IRE,ITA,...,0,-17,0,1,0,-17,1,0,0,-17
123,2,3,Ireland,Italy,Keith,45,10,1,IRE,ITA,...,-9,-10,0,0,0,-19,0,0,0,-19
124,2,3,Ireland,Italy,Ellie,40,15,1,IRE,ITA,...,-4,-15,0,0,0,-19,0,0,0,-19
125,2,3,Ireland,Italy,The Baglan Strangler,33,12,1,IRE,ITA,...,-3,-12,0,0,0,-15,0,0,0,-15

In [15]:
# make a simpler table, i.e. by round and by total?

# round scores
cols = df2[['Round', 'Name', 'FinalScore']]
cols

rnd_grp = cols.groupby(['Round', 'Name']).sum()
rnd_grp

round_score = pd.merge(rnd_grp, df3, how='left', on=['Round', 'Name'])
round_score = round_score[['Round', 'Name', 'FinalScore', 'CorrectRoundBonus']]

round_score['TotalRoundScore'] = round_score[['FinalScore', 'CorrectRoundBonus']].sum(axis=1)
round_score

,Round,Name,FinalScore,CorrectRoundBonus,TotalRoundScore
0,1,Big D,-54,0,-54
1,1,CBP,-75,0,-75
2,1,Elise,-65,0,-65
3,1,Ellie,-67,0,-67
4,1,Ems,-55,0,-55
5,1,Ethan,-86,0,-86
6,1,Glennnn,-69,0,-69
7,1,Iesha,-48,0,-48
8,1,JC,-60,0,-60
9,1,Jess,-59,0,-59
10,1,Jon,-61,0,-61
11,1,Keith,-67,0,-67
12,1,Leigh,-79,0,-79
13,1,MP,-60,0,-60
14,1,Mike P,-60,0,-60
15,1,OJ,-85,0,-85
16,1,Serith,-36,5,-31
17,1,Stubert,-41,0,-41
18,1,The Baglan Strangler,-62,0,-62
19,1,The Hawk,-61,0,-61
20,1,Wazza,-90,0,-90
21,2,Big D,-37,5,-32
22,2,CBP,-60,5,-55
23,2,Elise,-29,5,-24
24,2,Ellie,-56,0,-56
25,2,Ems,-86,0,-86
26,2,Ethan,-67,0,-67
27,2,Glennnn,-50,0,-50
28,2,Iesha,-71,0,-71
29,2,JC,-45,0,-45
30,2,Jess,-60,0,-60
31,2,Jon,-35,5,-30
32,2,Keith,-51,0,-51
33,2,Leigh,-44,0,-44
34,2,MP,-44,5,-39
35,2,Mike P,-44,5,-39
36,2,OJ,-38,5,-33
37,2,Serith,-50,5,-45
38,2,Stubert,-80,0,-80
39,2,The Baglan Strangler,-57,0,-57
40,2,The Hawk,-40,5,-35
41,2,Wazza,-50,0,-50

In [16]:
# some results are -5 points off in Round 1 i.e. Ellie, JC, Keith, Leigh, Stubert
round_score[(round_score['Round']==1)]
df2[(df2['Name']=='JC') & (df2['Round']==1)]

# all round 2 scores are correct
round_score[(round_score['Round']==2)]

,Round,Name,FinalScore,CorrectRoundBonus,TotalRoundScore
21,2,Big D,-37,5,-32
22,2,CBP,-60,5,-55
23,2,Elise,-29,5,-24
24,2,Ellie,-56,0,-56
25,2,Ems,-86,0,-86
26,2,Ethan,-67,0,-67
27,2,Glennnn,-50,0,-50
28,2,Iesha,-71,0,-71
29,2,JC,-45,0,-45
30,2,Jess,-60,0,-60
31,2,Jon,-35,5,-30
32,2,Keith,-51,0,-51
33,2,Leigh,-44,0,-44
34,2,MP,-44,5,-39
35,2,Mike P,-44,5,-39
36,2,OJ,-38,5,-33
37,2,Serith,-50,5,-45
38,2,Stubert,-80,0,-80
39,2,The Baglan Strangler,-57,0,-57
40,2,The Hawk,-40,5,-35
41,2,Wazza,-50,0,-50

In [17]:
# overall score
names = df2[['Name', 'FinalScore']]

total_score = names.groupby(['Name']).sum().rename(columns={'FinalScore':'TotalScore'})
total_score

# a lot if people 5 points out again lol (Serith 10 points out)

                      TotalScore
Name
Big D                        -91
CBP                         -135
Elise                        -94
Ellie                       -123
Ems                         -141
Ethan                       -153
Glennnn                     -119
Iesha                       -119
JC                          -105
Jess                        -119
Jon                          -96
Keith                       -118
Leigh                       -123
MP                          -104
Mike P                      -104
OJ                          -123
Serith                       -86
Stubert                     -121
The Baglan Strangler        -119
The Hawk                    -101
Wazza                       -140

## Questions 

1. How do I get my files in? i.e. do I set a working directory or should they be saved as files in my branch as .gitignore files?
2. How will we be importing the data, i.e. what format? Data wrangling in pandas?
3. Can they predict a tie?
4. Should I create a round specific table to do CorrectRoundBonus at later date instead of where I've already done?
5. MP and Mike P are the same? Delete one
6.